version: "3.7"
services:
  mainline:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: "1.17.9-perl"
        BUILD_FILE: "debian.conf"
    image: app-mainline:1.17.9-perl
    ports:
      - "80:80"
  stable:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: "${DEFAULT_NGINX_VERSION}"
        BUILD_FILE: "debian.conf"
    image: app-stable:${DEFAULT_NGINX_VERSION}
    ports:
      - "81:80"
  alpine:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
      args:
        NGINX_VERSION: "1.17.9-alpine-perl"
        BUILD_FILE: "alpine.conf"
    image: app-alpine:1.17.9-alpine-perl
    ports:
      - "82:80"
